### PR TITLE
missed the fact that key should only be positive at this point...

### PR DESCRIPTION
**Pull request by jennyfothergill**
## Description

I realize the "fix" I submitted before was wrong because the key should only be positive at this point. This should be correct error handling.

## Motivation and Context

This will prevent negative out of bound indexing of the trajectory

Resolves: #???

## How Has This Been Tested?

I tested it with in and out of bounds values.

## Change log

fixed negative out of bounds IndexError for `HOOMDTrajectory.__getitem__()`
```

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/gsd/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**GSD Contributor Agreement**](https://github.com/glotzerlab/gsd/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/gsd/blob/master/doc/credits.rst).

### CODE REVIEW

**Comment by joaander** [comment]
@jennyfothergill please add a unit test to verify the correct behavior.

**Comment by joaander** [comment]
Also: change the base of this PR to `maint`

**Comment by jennyfothergill** [comment]
Hi Josh,
Just to check I should use nose to make the unit test, right? I was thinking to add it to tests/test_hoomd.py --> test_slicing_and_iteration(). Sorry if these are basic questions, I've never made a unit test before.

**Comment by joaander** [comment]
Yes. I suggest adding the new tests in `test_hoomd.test_iteration`. See the structure there that verifies the steps are indexed correctly. You should add tests that confirm the negative indexing works all the way back to frame 0, and an additional test that confirms the exception when attempting to index further back.

**Pull request merged**
